# global:
#   resolve_timeout: 5m

# route:
#   group_by: ['alertname']
#   group_wait: 10s
#   group_interval: 10s
#   repeat_interval: 1h
#   receiver: 'web.hook'
# receivers:
# - name: 'web.hook'
#   webhook_configs:
#   - url: 'http://127.0.0.1:5001/'
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']
global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'
 
route:
  receiver: 'slack-notifications'
 
receivers:
 - name: 'slack-notifications'
   slack_configs:
   - channel: '#prometheus-test'
     send_resolved: true